# Generated by Django 4.2.7 on 2024-05-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_contact_contact_date_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
